### ISSUE TITLE
Can't add Stars to rating

### ISSUE THREAD

**Issue by wsvincent** [RachelMinto/yelp#20]
Hi Rachel,

I heard your interview on LaunchSchool and checked out your repo. The Yelp clone is very nice, but there's a problem with adding ratings--I can't. See attached screenshot. Hope this helps.

https://cl.ly/3d3V0L1u2b3f

Best,

Will

**Comment by RachelMinto** [comment]
Hi Will,

Thank you for bringing this to my attention! I appreciate it. Everything is running fine locally, so it looks like it's an issue with the asset precompiling process for Heroku. So far I haven't been able to come up with a solution that allows me to load both the bootstrap file and my own .js file, so I'll keep looking into it.

Thanks,
Rachel

**Comment by RachelMinto** [comment]
Hi Will,

Life got in the way a bit this month, but I've now got the rating system fixed. Thanks again for the feedback!

Rachel
